### ISSUE TITLE
Not showing anything for 0.60.6 to 0.61.5 upgrade

### ISSUE THREAD

**Issue by elie222** [react-native-community/upgrade-helper#212] opened 2020-03-19 12:41 UTC
# Bug

The diff tool isn't showing a diff.

![image](https://user-images.githubusercontent.com/3090527/77068673-a1bf7200-69ef-11ea-8126-1cd7f722d104.png)

## React Native versions

0.60.6 to 0.61.5 upgrade

## Steps to reproduce

Go to this url: https://react-native-community.github.io/upgrade-helper/?from=0.60.6&to=0.61.5

Describe what you expected to happen:

1. Show the diff

**Comment by lucasbento** [comment] 2020-03-19 13:21
Thanks for creating the issue, this should be fixed now on the latest build.

This was caused by an automatic update of `react-diff-view` which was already reverted.

**Closed by lucasbento** 2020-03-19 13:21 UTC
